workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: 15.4
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS unsigned
        script: |
          flutter build ios --debug --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/Runner.app
          zip -r Runner.ipa Payload
    artifacts:
      - build/ios/iphoneos/Runner.ipa